### ISSUE TITLE
After login, where do you store the session token?

### ISSUE THREAD

**Issue by caalvinz** [domfarolino/angular2-login-seed#10]
Here is the login method. I can't find how and where the token is stored and how to send it to server. Could you give me some idea about this? Thanks.

```
login(user) {
    let body = JSON.stringify(user);
    let headers = new Headers();
    headers.append('Content-Type', 'application/json');

    return this.http.post(this._loginApi, body, <RequestOptionsArgs> {headers: headers, withCredentials: true})
                    .map((res: Response) => res)
                    .catch(this.handleError);
  }
```

**Comment by domfarolino** [comment]
The express server sends a `Set Cookie` header in the login response, the client is allowed to set the cookie as a result of the `withCredentials: true` option in the `<RequestOptionsArgs>`. Does this clear it up at all? I admit it is a little odd looking with out explicit client side storage logic

**Comment by caalvinz** [comment]
Got it, thanks a lot.

**Comment by domfarolino** [comment]
@Ewebalvin feel free to email me with any questions: domfarolino@gmail.com
