### ISSUE TITLE
Update to rc5

### ISSUE THREAD

**Issue by StevePavlin** [domfarolino/angular2-login-seed#11]
The project should be updated to rc5, implementing the @NgModule decorator wherever possible.

https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by domfarolino** [comment]
You're absolutely right. I've been meaning to look into the changes but have been really busy (shitty excuse I know). Hopefully I can get to it soon, however if you want to take a stab at it be my guest.

**Comment by domfarolino** [comment]
Issue needs updated to reflect the app needing updated to final release
