### ISSUE TITLE
Update to Angular2 latest release

### ISSUE THREAD

**Issue by domfarolino** [domfarolino/angular2-login-seed#12]
I won't be able to get to this update for another week or so but if someone wants to take a stab at updating this Angular2 app from rc.4 => 2.0.0 latest release that would be great!

**Comment by jleajones** [comment]
@domfarolino, I think i can take care of this.

**Comment by domfarolino** [comment]
@jleajones cool go ahead and take a stab at it I appreciate it

**Comment by wiewioraseb** [comment]
@jleajones are you still on this issue? If not, I will take a look

**Comment by jleajones** [comment]
@wiewioraseb yeah. All good, just had to update some other dep. making PR today.

**Comment by wiewioraseb** [comment]
@jleajones Ok

**Comment by domfarolino** [comment]
@jleajones Thanks 👍

**Comment by domfarolino** [comment]
@jleajones  how's it coming?

**Comment by wiewioraseb** [comment]
@domfarolino I would take this one, but I can't make it run. I get lot of issues when running 'npm start' connected with angular-cli: 

> It seems like you're using a project generated using an old version of the Angular CLI.
> The latest CLI now uses webpack and includes a lot of improvements, include a simpler
> workflow, a faster build and smaller bundles.
> 
> To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
> https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12

I got angular-cli installed globally, tried reinstalling, cleaning cache etc. Didn't work.

**Comment by domfarolino** [comment]
@wiewioraseb I'm hoping to take a close look at it this week. We just finished organizing my university's hackathon so my schedule should be freeing up finally. If you get anywhere with it let me know, but I'll start taking cracks at it.

**Comment by wiewioraseb** [comment]
I could take this issue and migrate project to newest Angular2 version, but fixing the stuff with angular-cli should be in different issue. Changes would be too complex and hard too maintain for one pull request. The other thing is, someone would have to verify that I'm not the only one with the angular-cli errors.
