### ISSUE TITLE
demo doesnt run

### ISSUE THREAD

**Issue by mattmeye** [domfarolino/angular2-login-seed#14]

**Comment by domfarolino** [comment]
What issues are you particularly seeing? I'll look into this further today, sorry.

**Comment by domfarolino** [comment]
I have no issue pulling it down and running. Can you walk me through the steps you're taking?

**Comment by mattmeye** [comment]
click on the demo button in git readme: https://chinocode.com/angular2-login-seed 404

**Comment by domfarolino** [comment]
Ahh, sorry. Outdated link. Should be fixed now. Updated to https://domfarolino.com/angular2-login-seed
