### ISSUE TITLE
Host Parameter

### ISSUE THREAD

**Issue by duard** [domfarolino/angular2-login-seed#15]
How can I change the host address when running this ?
I try to add --host 192.168.2.3 here

`    "start": "ng serve --host 192.168.2.3",
`

but I cant login or register after this change.

**Comment by domfarolino** [comment]
What exactly are you trying to do? Run the Angular app on a different port? Run the Angular app on a different machine? I have no experience trying to run an Angular app on a different machine with the `--host` flag however some of the comments in [this](https://github.com/angular/angular-cli/issues/889) article may be helpful.

I think the issue you're seeing is outside the scope of this project though. Let me know what you think

**Comment by domfarolino** [comment]
Still having problems with this?
