### ISSUE TITLE
Demo on Heroku not working

### ISSUE THREAD

**Issue by PhilippeCorreges** [domfarolino/angular2-login-seed#2]
Hi
The link for the demo goes to a blank page.

Best Regards

Phiippe

**Comment by domfarolino** [comment]
You're just seeing a blank page? The link works for me and loads properly for my devices. Try it again and check out the console to see if something is throwing errors.

**Comment by PhilippeCorreges** [comment]
OK. It takes a while to open but it opens correctly. Maybe the app was sleeping.

thanks !

**Comment by domfarolino** [comment]
Also could be the angular router just being slow, or the background image taking too long to download. I'll try and take care of this
