### ISSUE TITLE
The angular2-login-seed.herokuapp.com page isn’t working

### ISSUE THREAD

**Issue by IvanYurchenko** [domfarolino/angular2-login-seed#24]
I'm getting such error when trying to sign in via Google: 

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_105836/tMJ4rpJR5vtXilhvTWFEVEBRlmOBk3/angular2-login-seed.herokuapp.com%2B2017-02-17%2B01-06-20.png?Expires=1487372979&Signature=Xpa0uhutWIwJHgR2r4ggCzMzaaHFqjtOEy67zlj0bQgM4O5oym-pHDGSDf54MTMwYFb54U16cVqaXxY42S9ywUHTp28Eo2d6djnakseBxhNUGrHnUqhRjWGbRt5kAs9BjF12-RuxOTM4RhHU6CImFtUAgY-8pPRYQxFwDZJObXFZnjpdNycpd1nbkD00AARqgEPXD0KopqTWYD5f3nbfZnaZp~5GcvuTQYkjS31eBriju6eYjAhV6smRdvm8RSZWDFSq~3tKvy6dImByt8a8VhsCGmwUqBCvDvtoHyOYmuHpxV~UnVqlxPROkfiikdAV3q8XDHSueTu76RSpYI9lSA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

Clearing cookies didn't help. I haven't faced this error when I opened the app last time a week ago. It occurs in both Chrome/Safari. If you think that the problem is on my side could you give some advice on how to fix it?

This is the console output:
```
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
main.ts:13Bootstrap success
https://angular2-login-seed.herokuapp.com/api/authenticated Failed to load resource: the server responded with a status of 401 (Unauthorized)
https://angular2-login-seed.herokuapp.com/api/users/register Failed to load resource: the server responded with a status of 400 (Bad Request)
2https://angular2-login-seed.herokuapp.com/api/authenticated Failed to load resource: the server responded with a status of 401 (Unauthorized)
error_handler.js:47EXCEPTION: Response with status: 401 Unauthorized for URL: https://angular2-login-seed.herokuapp.com/api/authenticated
ErrorHandler.handleError @ error_handler.js:47
Subscriber.js:227Uncaught Response
5https://angular2-login-seed.herokuapp.com/api/authenticated Failed to load resource: the server responded with a status of 401 (Unauthorized)
zone.js:1382 GET https://angular2-login-seed.herokuapp.com/api/authenticated 401 (Unauthorized)
```

**Comment by domfarolino** [comment]
See my comment on #25
