### ISSUE TITLE
Why deprecated

### ISSUE THREAD

**Issue by stefanwalther** [domfarolino/angular2-login-seed#26]
Hi,

why do you state it's deprecated?
I cannot find any information explaining why it has been declared as deprecated.

Thx in advance for your answer!
Regards
Stefan

**Comment by domfarolino** [comment]
Hi! It has only been deprecated because I haven't had the time to keep up with like I wish I could. Am currently looking for a maintainer to revive it though so if you're interested.....

Going to close this issue, but if you want to still comment, go ahead and we can talk...or email.

**Comment by stefanwalther** [comment]
OK, thx for clarification.
