### ISSUE TITLE
[Maintainer Wanted]

### ISSUE THREAD

**Issue by domfarolino** [domfarolino/angular2-login-seed#28]
A number of people have opened issues on this repository asking why it has been deprecated (since there is not any information about this in the README etc) and why certain portions of the live app (backend) do not work anymore. Answer: I let the hosting for the database expire (though I have a dump of all the data) because I no longer have the time to maintain this project the way I wish I could.

**However**, this provides a good opportunity for the community, as I'm looking for a **maintainer** to step in! If I could give someone worthy, **write-access** to the repository so they can build it up again and update all the dependencies etc that would be a huge help. If anyone is interested in contributing please let me know via email (domfarolino@gmail.com) or comment on this issue and I'd be happy to talk to you. Submitting a PR to update the application's dependencies and make it work with all the new jazz would be a great first step :)

**Comment by nitishvu** [comment]
Hi I am interested to contribute :)

**Comment by domfarolino** [comment]
If you want, you can get started trying to update the dependencies, as they are very much out of date. A working application with latest dependencies (aka updating this app) would be a huge start!

**Comment by nitishvu** [comment]
Yes , i will get familiar with the environment . till now i was using svn.
I am new to git , need to understand how to update.
do you want me to create new branch??

On Tue, Mar 28, 2017 at 12:42 PM, Dominic Farolino <notifications@github.com

**Comment by cristianounix** [comment]
@nitishvu @domfarolino 
Has anyone started to update the packages?
<img width="861" alt="screen shot 2017-04-04 at 22 11 10" src="https://cloud.githubusercontent.com/assets/694280/24685406/b5161990-1983-11e7-9445-e7da526bf790.png">

**Comment by domfarolino** [comment]
@cristianounix Not to my knowledge no. If you'd like to start that would be great! Let me know if you need help, though I haven't messed with the angular-specific stuff in a while. You'll probably need to run the server locally but I'd like to migrate the server to use mongodb/mongoose I think that would be a lot better and need done for sure.

**Comment by nitishvu** [comment]
Hi @domfarolino @cristianounix 

I have updated with Dependencies and replaced the deprecated modules.
will  try update with Mongodb
you can check the code @[GitHub](https://github.com/nitishvu/angular2-login-seed/)

**Comment by domfarolino** [comment]
Could you (whoever is tackling this) submit a PR with the suggested changes/updates? That would be great.

/cc @nitishvu @cristianounix

**Comment by Smurfy303** [comment]
Hi @nitishvu ,
I refered your updated dependencies it runs well but while register or using google login it gives me error as "User already exists". Could you please help me ??

**Comment by domfarolino** [comment]
Any updates on this @nitishvu @cristianounix? There's no ultimate rush or anything, just checking it see if anyone has looked at it since. If you'd like to submit a PR that would be cool.

**Comment by domfarolino** [comment]
Closing this and opening new issue for hacktoberfest
