### ISSUE TITLE
npm ERR! peerinvalid Peer

### ISSUE THREAD

**Issue by caalvinz** [domfarolino/angular2-login-seed#8]
There is an error while running "npm install".

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/forms@0.2.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular2-material/input@2.0.0-alpha.6 wants @angular/forms@^0.1.0
```

**Comment by domfarolino** [comment]
Interesting. I only get `npm WARN` not `ERR!` when doing a fresh install.

@Ewebalvin I know forms were updated just after material2 went to alpha.6 but they should still be compatible. Are you able to run the app locally despite this error?

**Comment by caalvinz** [comment]
Yes, I just tried. It could run locally even the error was still there.
